	ethernet_sys u0 (
		.clk_50_clk                             (<connected-to-clk_50_clk>),                             //                        clk_50.clk
		.clk_ref_125_clk                        (<connected-to-clk_ref_125_clk>),                        //                   clk_ref_125.clk
		.eth_tse_0_mac_mdio_connection_mdc      (<connected-to-eth_tse_0_mac_mdio_connection_mdc>),      // eth_tse_0_mac_mdio_connection.mdc
		.eth_tse_0_mac_mdio_connection_mdio_in  (<connected-to-eth_tse_0_mac_mdio_connection_mdio_in>),  //                              .mdio_in
		.eth_tse_0_mac_mdio_connection_mdio_out (<connected-to-eth_tse_0_mac_mdio_connection_mdio_out>), //                              .mdio_out
		.eth_tse_0_mac_mdio_connection_mdio_oen (<connected-to-eth_tse_0_mac_mdio_connection_mdio_oen>), //                              .mdio_oen
		.lcd_16207_0_external_RS                (<connected-to-lcd_16207_0_external_RS>),                //          lcd_16207_0_external.RS
		.lcd_16207_0_external_RW                (<connected-to-lcd_16207_0_external_RW>),                //                              .RW
		.lcd_16207_0_external_data              (<connected-to-lcd_16207_0_external_data>),              //                              .data
		.lcd_16207_0_external_E                 (<connected-to-lcd_16207_0_external_E>),                 //                              .E
		.leds_crs                               (<connected-to-leds_crs>),                               //                          leds.crs
		.leds_link                              (<connected-to-leds_link>),                              //                              .link
		.leds_panel_link                        (<connected-to-leds_panel_link>),                        //                              .panel_link
		.leds_col                               (<connected-to-leds_col>),                               //                              .col
		.leds_an                                (<connected-to-leds_an>),                                //                              .an
		.leds_char_err                          (<connected-to-leds_char_err>),                          //                              .char_err
		.leds_disp_err                          (<connected-to-leds_disp_err>),                          //                              .disp_err
		.mac_misc_ff_tx_crc_fwd                 (<connected-to-mac_misc_ff_tx_crc_fwd>),                 //                      mac_misc.ff_tx_crc_fwd
		.mac_misc_ff_tx_septy                   (<connected-to-mac_misc_ff_tx_septy>),                   //                              .ff_tx_septy
		.mac_misc_tx_ff_uflow                   (<connected-to-mac_misc_tx_ff_uflow>),                   //                              .tx_ff_uflow
		.mac_misc_ff_tx_a_full                  (<connected-to-mac_misc_ff_tx_a_full>),                  //                              .ff_tx_a_full
		.mac_misc_ff_tx_a_empty                 (<connected-to-mac_misc_ff_tx_a_empty>),                 //                              .ff_tx_a_empty
		.mac_misc_rx_err_stat                   (<connected-to-mac_misc_rx_err_stat>),                   //                              .rx_err_stat
		.mac_misc_rx_frm_type                   (<connected-to-mac_misc_rx_frm_type>),                   //                              .rx_frm_type
		.mac_misc_ff_rx_dsav                    (<connected-to-mac_misc_ff_rx_dsav>),                    //                              .ff_rx_dsav
		.mac_misc_ff_rx_a_full                  (<connected-to-mac_misc_ff_rx_a_full>),                  //                              .ff_rx_a_full
		.mac_misc_ff_rx_a_empty                 (<connected-to-mac_misc_ff_rx_a_empty>),                 //                              .ff_rx_a_empty
		.pio_0_external_connection_export       (<connected-to-pio_0_external_connection_export>),       //     pio_0_external_connection.export
		.pio_1_external_connection_export       (<connected-to-pio_1_external_connection_export>),       //     pio_1_external_connection.export
		.reset_reset_n                          (<connected-to-reset_reset_n>),                          //                         reset.reset_n
		.reset_0_reset_n                        (<connected-to-reset_0_reset_n>),                        //                       reset_0.reset_n
		.serdes_txp                             (<connected-to-serdes_txp>),                             //                        serdes.txp
		.serdes_rxp                             (<connected-to-serdes_rxp>),                             //                              .rxp
		.serdes_control_rx_recovclkout          (<connected-to-serdes_control_rx_recovclkout>),          //                serdes_control.rx_recovclkout
		.serdes_control_reconfig_clk            (<connected-to-serdes_control_reconfig_clk>),            //                              .reconfig_clk
		.serdes_control_reconfig_togxb          (<connected-to-serdes_control_reconfig_togxb>),          //                              .reconfig_togxb
		.serdes_control_reconfig_fromgxb        (<connected-to-serdes_control_reconfig_fromgxb>),        //                              .reconfig_fromgxb
		.serdes_control_reconfig_busy           (<connected-to-serdes_control_reconfig_busy>),           //                              .reconfig_busy
		.sram_clk_clk                           (<connected-to-sram_clk_clk>),                           //                      sram_clk.clk
		.sram_cntrlr_0_conduit_end_dq           (<connected-to-sram_cntrlr_0_conduit_end_dq>),           //     sram_cntrlr_0_conduit_end.dq
		.sram_cntrlr_0_conduit_end_addr         (<connected-to-sram_cntrlr_0_conduit_end_addr>),         //                              .addr
		.sram_cntrlr_0_conduit_end_sram_bwan    (<connected-to-sram_cntrlr_0_conduit_end_sram_bwan>),    //                              .sram_bwan
		.sram_cntrlr_0_conduit_end_sram_bwbn    (<connected-to-sram_cntrlr_0_conduit_end_sram_bwbn>),    //                              .sram_bwbn
		.sram_cntrlr_0_conduit_end_sram_cen     (<connected-to-sram_cntrlr_0_conduit_end_sram_cen>),     //                              .sram_cen
		.sram_cntrlr_0_conduit_end_sram_oen     (<connected-to-sram_cntrlr_0_conduit_end_sram_oen>),     //                              .sram_oen
		.sram_cntrlr_0_conduit_end_sram_wen     (<connected-to-sram_cntrlr_0_conduit_end_sram_wen>)      //                              .sram_wen
	);

